In [82]:
import pandas as pd

In [83]:
df_ans = pd.read_csv("../preprocess_test_data.csv", index_col = 0)
df_ans['text_clean'] = df_ans['text_clean'].fillna('neutral')
df_ans.head()

,_id,text,text_clean
0,60c5d6bf5659ea5e55deffcb,Fewer people coming in for vaccinations. So sa...,fewer peopl come vaccin sad nurs covidvaccin vumc
1,60c5d6bf5659ea5e55df028c,@MattHancock This may all be true. But... What...,may true piss big dom
2,60c5d6bf5659ea5e55def377,@Layla_EFC I’ve unfollowed him the wanker,unfollow wanker
3,60c5d6bf5659ea5e55def4c7,You guys are losing it all over the world. The...,guy lose world jung label islamophobia
4,60c5d6bf5659ea5e55df01a6,"And thus death laughs... It is sad merriment, ...",thus death laugh sad merriment still covid ind...

In [2]:
!pip install scikit-learn == 0.13

ERROR: Invalid requirement: '=='

In [9]:
import sklearn
sklearn.__version__

'0.23.2'

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidconverter = TfidfVectorizer(max_features=2000, min_df= 2)
X_test = tfidconverter.fit_transform(df_ans['text_clean']).toarray()

In [85]:
print(len(X_test[1]))

1847

In [86]:
import pickle
dt1 = pickle.load(open('finalized_svc_model1.sav', 'rb'))
dt2 = pickle.load(open('finalized_rfc_model1.sav', 'rb'))
dt3 = pickle.load(open('finalized_Knc_model1.sav', 'rb'))

In [87]:
X_test = X_test[:, :1741]

In [88]:
pred_df = pd.DataFrame()
pred_dt = dt1.predict(X_test)
pred_df['SVC'] = pred_dt
pred_rft = dt2.predict(X_test)
pred_df['RandomForest'] = pred_dt
pred_svm = dt3.predict(X_test)
pred_df['Kneighbors'] = pred_dt

df_ans = df_ans.drop(['text', 'text_clean'], axis = 1)
df_ans = df_ans.reset_index()
df_ans = df_ans.drop(['index'], axis = 1)
df_ans.head()

                        _id
0  60c5d6bf5659ea5e55deffcb
1  60c5d6bf5659ea5e55df028c
2  60c5d6bf5659ea5e55def377
3  60c5d6bf5659ea5e55def4c7
4  60c5d6bf5659ea5e55df01a6

In [89]:
df_ans['label'] = pd.Series(pred_dt)
df_ans.to_csv('tfidf_svc.csv', index=False)
df_ans.head(20)

                         _id  label
0   60c5d6bf5659ea5e55deffcb      3
1   60c5d6bf5659ea5e55df028c      1
2   60c5d6bf5659ea5e55def377      1
3   60c5d6bf5659ea5e55def4c7      1
4   60c5d6bf5659ea5e55df01a6      3
5   60c5d6bf5659ea5e55def837      1
6   60c5d6bf5659ea5e55def6ec      1
7   60c5d6bf5659ea5e55def29e      1
8   60c5d6bf5659ea5e55defa01      2
9   60c5d6bf5659ea5e55def464      0
10  60c5d6bf5659ea5e55df020f      1
11  60c5d6bf5659ea5e55defb48      1
12  60c5d6bf5659ea5e55def1a8      1
13  60c5d6bf5659ea5e55defc80      1
14  60c5d6bf5659ea5e55defc3e      3
15  60c5d6bf5659ea5e55def2e2      1
16  60c5d6bf5659ea5e55defbd6      3
17  60c5d6bf5659ea5e55defc41      3
18  60c5d6bf5659ea5e55df0176      1
19  60c5d6bf5659ea5e55df027b      0

In [90]:
df_ans['label'] = pd.Series(pred_rft)
df_ans.to_csv('tfdif_rft.csv', index= False)
df_ans.head(20)

                         _id  label
0   60c5d6bf5659ea5e55deffcb      3
1   60c5d6bf5659ea5e55df028c      1
2   60c5d6bf5659ea5e55def377      1
3   60c5d6bf5659ea5e55def4c7      1
4   60c5d6bf5659ea5e55df01a6      3
5   60c5d6bf5659ea5e55def837      1
6   60c5d6bf5659ea5e55def6ec      3
7   60c5d6bf5659ea5e55def29e      1
8   60c5d6bf5659ea5e55defa01      3
9   60c5d6bf5659ea5e55def464      1
10  60c5d6bf5659ea5e55df020f      1
11  60c5d6bf5659ea5e55defb48      1
12  60c5d6bf5659ea5e55def1a8      1
13  60c5d6bf5659ea5e55defc80      1
14  60c5d6bf5659ea5e55defc3e      0
15  60c5d6bf5659ea5e55def2e2      1
16  60c5d6bf5659ea5e55defbd6      1
17  60c5d6bf5659ea5e55defc41      1
18  60c5d6bf5659ea5e55df0176      1
19  60c5d6bf5659ea5e55df027b      1

In [95]:
df_ans['label'] = pd.Series(pred_svm)
df_ans.to_csv('tfdif_svm.csv', index= False)
df_ans.head(20)

                         _id  label
0   60c5d6bf5659ea5e55deffcb      3
1   60c5d6bf5659ea5e55df028c      3
2   60c5d6bf5659ea5e55def377      1
3   60c5d6bf5659ea5e55def4c7      1
4   60c5d6bf5659ea5e55df01a6      3
5   60c5d6bf5659ea5e55def837      1
6   60c5d6bf5659ea5e55def6ec      1
7   60c5d6bf5659ea5e55def29e      1
8   60c5d6bf5659ea5e55defa01      1
9   60c5d6bf5659ea5e55def464      1
10  60c5d6bf5659ea5e55df020f      1
11  60c5d6bf5659ea5e55defb48      1
12  60c5d6bf5659ea5e55def1a8      3
13  60c5d6bf5659ea5e55defc80      1
14  60c5d6bf5659ea5e55defc3e      3
15  60c5d6bf5659ea5e55def2e2      1
16  60c5d6bf5659ea5e55defbd6      3
17  60c5d6bf5659ea5e55defc41      3
18  60c5d6bf5659ea5e55df0176      1
19  60c5d6bf5659ea5e55df027b      1

In [93]:
pred_df['res'] = pred_df.mode(axis = 1)[0].astype(int)
pred_df.head()
res = pred_df['res'].tolist()

In [94]:
res

[3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 3,
 1,
 0,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 3,
 1,
 0,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 1,
 3,
 3,
 3,
 3,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 1,
 3,
 0,
 0,
 2,
 1,
 3,
 1,
 0,
 1,
 1,
 3,
 3,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 3,
 2,
 0,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 0,
 1,
 1,
 1,
 1,
 3,
 3,
 0,
 1,
 0,
 3,
 1,
 1,
 1,
 3,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 1,
 0,
 1,
 3,
 2,
 1,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 3,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 3,
 1,
 0,
 3,
 1,
 0,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 2,
 1,
 3,
 0,
 2,
 1,
 3,
 1,
 2,
 0,
 1,
 1,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 3,
 1,
 1,
 3,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 3,
 1,
 2,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 3,
 2,
 3,
 0,
 3,
 1,
 3,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 0,
 1,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 3,
 0,
 1,
 3,
 1,
 0,
 3,
 1,
 3,
 0,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 0,
 1,
 0,
 3,
 1,
 0,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 1,
 1,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 2,
 0,
 2,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 0,
 3,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 0,
 3,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 1,
 3,
 3,
 0,
 1,
 3,
 1,
 1,
 2,
 1,
 3,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 3,
 1,
 0,
 3,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 0,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 1,
 2,
 1,
 3,
 3,
 0,
 0,
 1,
 3,
 1,
 1,
 3,
 1,
 3,
 0,
 3,
 3,
 3,
 1,
 3,
 2,
 3,
 2,
 1,
 0,
 2,
 1,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 2,
 3,
 1,
 1,
 1,
 3,
 0,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 0,
 0,
 0,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 0,
 0,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 3,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 1,
 3,
 0,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 3,
 0,
 1,
 3,
 3,
 0,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 3,
 0,
 1,
 1,
 1,
 3,
 0,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 3,
 0,
 3,
 3,
 1,
 0,
 0,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 2,
 1,
 3,
 3,
 0,
 1,
 3,
 1,
 3,
 0,
 1,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 0,
 3,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 3,
 1,
 3,
 1,
 3,
 3,
 1,
 0,
 0,
 1,
 3,
 0,
 3,
 1,
 2,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 3,
 1,
 3,
 3,
 1,
 3,
 1,
 1,
 2,
 1,
 3,
 3,
 1,
 0,
 0,
 2,
 3,
 1,
 2,
 2,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 3,
 1,
 0,
 0,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 1,
 0,
 3,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 3,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 1,
 1,
 1,
 0,
 3,
 2,
 1,
 3,
 3,
 3,
 1,
 ...]

In [97]:
res[0]

3

In [100]:
label = []
for i in range(len(res)):
    ans = res[i]
    if (ans == 0):
        label.append('HATE')
    elif (ans == 1):
        label.append('NONE')
    elif (ans == 2):
        label.append('OFFN')
    elif (ans == 3):
        label.append('PRFN')

In [101]:
label

['PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'OFFN',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'HATE',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'OFFN',
 'HATE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'OFFN',
 'NONE',
 'HATE',
 'HATE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'OFFN',
 'NONE',
 'PRFN',
 'HATE',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'OFFN',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'HATE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'OFFN',
 'PRFN',
 'HATE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'OFFN',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'OFFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'OFFN',
 'NONE',
 'OFFN',
 'NONE',
 'OFFN',
 'HATE',
 'OFFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'OFFN',
 'PRFN',
 'OFFN',
 'NONE',
 'HATE',
 'OFFN',
 'NONE',
 'OFFN',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'PRFN',
 'OFFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'HATE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'OFFN',
 'OFFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'HATE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'HATE',
 'PRFN',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'OFFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'OFFN',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'HATE',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'HATE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'PRFN',
 'HATE',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'HATE',
 'NONE',
 'NONE',
 'OFFN',
 'PRFN',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'HATE',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'OFFN',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'HATE',
 'HATE',
 'OFFN',
 'PRFN',
 'NONE',
 'OFFN',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'HATE',
 'HATE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'HATE',
 'HATE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'OFFN',
 'NONE',
 'PRFN',
 'NONE',
 'OFFN',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'PRFN',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'OFFN',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'PRFN',
 'HATE',
 'PRFN',
 'NONE',
 'HATE',
 'PRFN',
 'NONE',
 'HATE',
 'NONE',
 'NONE',
 'NONE',
 'HATE',
 'PRFN',
 'OFFN',
 'NONE',
 'PRFN',
 'PRFN',
 'PRFN',
 'NONE',
 ...]

In [107]:
df_res = pd.DataFrame()
df_res['_id'] = df_ans['_id']
df_res['label'] = label

In [108]:
df_res

                           _id label
0     60c5d6bf5659ea5e55deffcb  PRFN
1     60c5d6bf5659ea5e55df028c  NONE
2     60c5d6bf5659ea5e55def377  NONE
3     60c5d6bf5659ea5e55def4c7  NONE
4     60c5d6bf5659ea5e55df01a6  PRFN
...                        ...   ...
1276  60c5d6bf5659ea5e55def74c  HATE
1277  60c5d6bf5659ea5e55df0380  NONE
1278  60c5d6bf5659ea5e55defaeb  NONE
1279  60c5d6bf5659ea5e55df03c3  NONE
1280  60c5d6bf5659ea5e55def60b  OFFN

[1281 rows x 2 columns]

In [109]:
df_res.to_csv('final.csv', index=False)

In [110]:
f_ans = pd.read_csv("./tfdif_rft.csv", index_col = 0)

df_ans.head()

                        _id  label
0  60c5d6bf5659ea5e55deffcb      3
1  60c5d6bf5659ea5e55df028c      3
2  60c5d6bf5659ea5e55def377      1
3  60c5d6bf5659ea5e55def4c7      1
4  60c5d6bf5659ea5e55df01a6      3

In [111]:
res = f_ans['label']
res

_id
60c5d6bf5659ea5e55deffcb    3
60c5d6bf5659ea5e55df028c    1
60c5d6bf5659ea5e55def377    1
60c5d6bf5659ea5e55def4c7    1
60c5d6bf5659ea5e55df01a6    3
                           ..
60c5d6bf5659ea5e55def74c    1
60c5d6bf5659ea5e55df0380    1
60c5d6bf5659ea5e55defaeb    1
60c5d6bf5659ea5e55df03c3    1
60c5d6bf5659ea5e55def60b    3
Name: label, Length: 1281, dtype: int64

In [112]:
label = []
for i in range(len(res)):
    ans = res[i]
    if (ans == 0):
        label.append('HATE')
    elif (ans == 1):
        label.append('NONE')
    elif (ans == 2):
        label.append('OFFN')
    elif (ans == 3):
        label.append('PRFN')

In [113]:
df_res = pd.DataFrame()
df_res['_id'] = df_ans['_id']
df_res['label'] = label

In [114]:
df_res

                           _id label
0     60c5d6bf5659ea5e55deffcb  PRFN
1     60c5d6bf5659ea5e55df028c  NONE
2     60c5d6bf5659ea5e55def377  NONE
3     60c5d6bf5659ea5e55def4c7  NONE
4     60c5d6bf5659ea5e55df01a6  PRFN
...                        ...   ...
1276  60c5d6bf5659ea5e55def74c  NONE
1277  60c5d6bf5659ea5e55df0380  NONE
1278  60c5d6bf5659ea5e55defaeb  NONE
1279  60c5d6bf5659ea5e55df03c3  NONE
1280  60c5d6bf5659ea5e55def60b  PRFN

[1281 rows x 2 columns]

In [115]:
df_res.to_csv('task2rft.csv', index=False)

In [117]:
f_ans = pd.read_csv("./tfdif_svm.csv", index_col = 0)

df_ans.head()

                        _id  label
0  60c5d6bf5659ea5e55deffcb      3
1  60c5d6bf5659ea5e55df028c      3
2  60c5d6bf5659ea5e55def377      1
3  60c5d6bf5659ea5e55def4c7      1
4  60c5d6bf5659ea5e55df01a6      3

In [118]:
res = f_ans['label']
res

_id
60c5d6bf5659ea5e55deffcb    3
60c5d6bf5659ea5e55df028c    3
60c5d6bf5659ea5e55def377    1
60c5d6bf5659ea5e55def4c7    1
60c5d6bf5659ea5e55df01a6    3
                           ..
60c5d6bf5659ea5e55def74c    1
60c5d6bf5659ea5e55df0380    1
60c5d6bf5659ea5e55defaeb    1
60c5d6bf5659ea5e55df03c3    1
60c5d6bf5659ea5e55def60b    1
Name: label, Length: 1281, dtype: int64

In [119]:
label = []
for i in range(len(res)):
    ans = res[i]
    if (ans == 0):
        label.append('HATE')
    elif (ans == 1):
        label.append('NONE')
    elif (ans == 2):
        label.append('OFFN')
    elif (ans == 3):
        label.append('PRFN')

In [120]:
df_res = pd.DataFrame()
df_res['_id'] = df_ans['_id']
df_res['label'] = label

In [121]:
df_res

                           _id label
0     60c5d6bf5659ea5e55deffcb  PRFN
1     60c5d6bf5659ea5e55df028c  PRFN
2     60c5d6bf5659ea5e55def377  NONE
3     60c5d6bf5659ea5e55def4c7  NONE
4     60c5d6bf5659ea5e55df01a6  PRFN
...                        ...   ...
1276  60c5d6bf5659ea5e55def74c  NONE
1277  60c5d6bf5659ea5e55df0380  NONE
1278  60c5d6bf5659ea5e55defaeb  NONE
1279  60c5d6bf5659ea5e55df03c3  NONE
1280  60c5d6bf5659ea5e55def60b  NONE

[1281 rows x 2 columns]

In [122]:
df_res.to_csv('task2knc.csv', index=False)